### ISSUE TITLE
zk: node does not exist

### ISSUE THREAD

**Issue by sparkthu** [wvanbergen/kafka#107]
I tried the example, but failed with a working kafka. The topic and zookeeper configurations are right.

  -group="click1": The name of the consumer group, used for coordination and load balancing
  -topics="bjcnc_nginx_nginx_newmysql0": The comma-separated list of topics to consume
  -zookeeper="10.16.13.133:2181,10.16.13.134:2181,10.16.13.135:2181,10.16.13.136:2181,10.16.13.137:2181/realtime-monitor-newmysql": A comma-separated Zookeeper connection string (e.g. `zookeeper1.local:2181,zookeeper2.local:2181,zookeeper3.local:2181`)
2016/10/22 17:30:38 Before JoinConsuerGroup, consumerGroup: click1 , nodes: [10.16.13.133:2181 10.16.13.134:2181 10.16.13.135:2181 10.16.13.136:2181 10.16.13.137:2181] , root: /realtime-monitor-newmysql
2016/10/22 17:30:38 Connected to 10.16.13.137:2181
2016/10/22 17:30:38 Authenticated: id=384865011391368701, timeout=4000
2016/10/22 17:30:38 Re-submitting `0` credentials after reconnect
2016/10/22 17:30:38 Recv loop terminated: err=EOF
2016/10/22 17:30:38 zk: node does not exist

**Comment by anxiousmodernman** [comment]
I get this error too. What is a potential cause?
