### ISSUE TITLE
Clarify Kafka version support

### ISSUE THREAD

**Issue by mcandre** [wvanbergen/kafka#115]
As of Kafka 0.9, users are encouraged to use Kafka broker addresses for auto-discovery, rather than the ZooKeeper connection details that the `kafka.NewConsumerGroup()` constructor expects.

Will wvanbergen/kafka support a more modern client constructor?

Which versions of Kafka has wvanbergen been tested against?

**Comment by wvanbergen** [comment]
No. This will eventually be added to sarama itself. This repo is not actively developed anymore, but will stick around for people that are stuck on the 0.8 model.

**Comment by mcandre** [comment]
Thanks for the clarification.

Is wvanbergen/kafka compatible with Kafka 0.9, or just 0.8?

**Comment by wvanbergen** [comment]
It works with 0.9 and 0.10 as well, because the low level APIs it uses have not been changed in the newer Kafka versions.
