### ISSUE TITLE
Upgrading to kafka based offset storage

### ISSUE THREAD

**Issue by sagard** [wvanbergen/kafka#123]
I am planning to upgrade sarama clients from 0.8 to latest version and use sarama-cluster. I see that offset will be committed to kafka now.  

On Apache Kafka page it says that for doing migration from zk based storage to kafka you need to do following:
Set offsets.storage=kafka and dual.commit.enabled=true in your consumer config.

I cannot find these properties anywhere? Does anyone know if we need to set it and where?

**Comment by wvanbergen** [comment]
Those properties are specific to the JVM client. This go client doesn't support it, and probably won't support it in the future, because it is no longer actively maintained.
