### ISSUE TITLE
ConsumerGroup.FlushOffsets() 

### ISSUE THREAD

**Issue by wangping886** [wvanbergen/kafka#127]
eg:cg, _ := consumergroup.JoinConsumerGroup("convert", kafkaTopics, Conf.Kafka.Consumer.ZKAddrs, config)
     in the same partision
     msg.offset is 187 but i did't  exec
                       `cg.CommitUpto(msg)
			cg.FlushOffsets()`
      and msg.offet is 188  exec
                      ` cg.CommitUpto(msg)
			cg.FlushOffsets()`
     and msg.offet is 189  didn't exec
                      ` cg.CommitUpto(msg)
			cg.FlushOffsets()`
      and then i restart my consumergroup .    cg.Messages()  will retrive 189,but 187 will not be retrived.     i 'm consufed by this

**Comment by wvanbergen** [comment]
This is working as intended. Zookeeper only keeps track of the latest offset that has been consumed, and assumes that everything before that offset has been handled. It doesn't keep track of every individual message.

**Comment by wangping886** [comment]
@wvanbergen  thanks for your reply . 
 To avoid miss message . when offset 187 's   process flow  fail .  I send this message to the same topic  to  let consummergroup to reconsummer, will it make sense ?

**Comment by wvanbergen** [comment]
There's different ways to this:

For "expected" failures (e.g. network blips, etc), you can:
- send the message to the same topic.
- send the message to a separate topic for failed messages (a so called dead letter queue)

For both options, you probably want to limit the amount of times you retry,

For "unexpected failures, that are not common, you can also consider sending the message to your bug tracking system so you can manually inspect them.
