### ISSUE TITLE
consumergroup hangs after sometime

### ISSUE THREAD

**Issue by lokeshverizon** [wvanbergen/kafka#23]
Hello,

I have observe when I use consumer group library, it works fine for short time after that it does not put offset in the zookeeper. After sometime, I only see the following offsets. 

/consumers/testgroup/offsets/mmetopic1/2:2502052
/consumers/testgroup/offsets/mmetopic1/1:2417072
/consumers/testgroup/offsets/mmetopic1/0:2482172

My producer keep writing new messages however consumer entries are still the same. When I try to instantiate another consumer, I get the following message (which might be useful for you to debug). 

[Sarama] 2014/08/30 04:48:37 Initializing new client
[Sarama] 2014/08/30 04:48:37 Fetching metadata from broker 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #1 at 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #3 at 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #2 at 10.1.129.1:9092
[Sarama] 2014/08/30 04:48:37 Successfully initialized new client
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.129.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 Initializing new client
[Sarama] 2014/08/30 04:48:37 Fetching metadata from broker 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #1 at 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #3 at 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 Registered new broker #2 at 10.1.129.1:9092
[Sarama] 2014/08/30 04:48:37 Successfully initialized new client
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.129.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.128.1:9092
[Sarama] 2014/08/30 04:48:37 Connected to broker 10.1.130.1:9092
[Sarama] 2014/08/30 04:48:37 [testgroup/d238b36d178a] Consumer instance registered (tpalkcoe3b9:66a33176-668a-4c89-b314-d238b36d178a).
init succeesfull
[Sarama] 2014/08/30 04:48:37 [testgroup/d238b36d178a] Currently registered consumers: 5
[Sarama] 2014/08/30 04:48:37 [testgroup/d238b36d178a] Started topic consumer for mmetopic1
[Sarama] 2014/08/30 04:48:37 [testgroup/d238b36d178a] Claiming 1 of 3 partitions for topic mmetopic1.
[Sarama] 2014/08/30 04:48:37 [testgroup/d238b36d178a] Started partition consumer for mmetopic1:2 at offset 2502052.
[Sarama] 2014/08/30 04:48:38 [testgroup/d238b36d178a] Stopping partition consumer for mmetopic1:2 at offset 0.
[Sarama] 2014/08/30 04:48:38 [testgroup/d238b36d178a] Stopped topic consumer for mmetopic1

**Comment by wvanbergen** [comment]
Sorry for the late reply. If it hangs next time, can you press CTRL+\ next time? That should dump the current status of all the goroutines. That helps me identifying where the deadlock is.

**Comment by wvanbergen** [comment]
Can you try with a more recent version, or with #72? Several bugs have been fixed sicne opening this issue.

Feel free to re-open this issue if you run into this again and have more information
