### ISSUE TITLE
Incompatible with latest Sarama Client

### ISSUE THREAD

**Issue by marcusking01** [wvanbergen/kafka#34]
The latest sarama client has separated it's consumers to have two channels for Messages and Errors rather than the one Events channel for both.  The latest consumergroup code has not been upgraded to that interface.  Any plans on updating?

**Comment by bayan** [comment]
The [update_to_latest_sarama](https://github.com/wvanbergen/kafka/tree/update_to_latest_sarama) branch works with the current sarama API.

**Comment by wvanbergen** [comment]
This has been fixed on master now.
