### ISSUE TITLE
Commit when CG closed

### ISSUE THREAD

**Issue by baconalot** [wvanbergen/kafka#50]
It would be nice if `zookeeperOffsetManager.commitOffsets()` got called from `ConsumerGroup.Close()`.
Right now stuff that is 'markedForCommit' after the last commit and before CG close is dropped.
Maybe also provide a `Commit()` method in the `OffsetManager` interface to be able to force commits from CG/clients.

**Comment by wvanbergen** [comment]
During a normal shutdown, there should be no difference between marked for commit, and committed, because the offsets are committed for every partition consumer as they wind down.

**Comment by wvanbergen** [comment]
Closing this - as this should already work. Also #72 improves how we keep track of offsets.
