### ISSUE TITLE
does this client support batch consume?

### ISSUE THREAD

**Issue by cch123** [wvanbergen/kafka#89]

**Comment by wvanbergen** [comment]
What do you mean by batches? The API will give you one message at the time,
but internally it consumes batches for increased performance.

**Comment by cch123** [comment]
Then can I control the inner batches size?
I haven't found a option to configure.

**Comment by wvanbergen** [comment]
Yes. The config struct includes the Sarama config struct, which includes
several variables to control the batching process. Look it up in the Sarama
docs.

**Comment by cch123** [comment]
thx!
